#!/usr/bin/env python3
"""Bring an edit made in the wiki's browser editor home, before the next sync can overwrite it.

Run by .github/workflows/wiki-edits.yml on every `gollum` event. For each page the event names:

* the last commit to the page is a seed or the scoreboard, or the page already equals wiki/<Page>.md
  → nothing to do;
* the page is generated by site/learn_export.py → an issue naming the lesson source to edit instead,
  with the edit as a diff, because the next export regenerates the page and drops the edit;
* the page is hand-written → the edited page goes onto a branch, and an issue carries the one-click
  pull request, so the edit reaches wiki/ and the next wiki/sync.sh keeps it.

Actions may not open pull requests in this repository (a setting, off), so this stops at the branch
and the link; a person opens the pull request. wiki/sync.sh refuses to overwrite an edit that has not
come home, so nothing is lost while it waits.
"""
from __future__ import annotations

import difflib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = os.environ["GITHUB_REPOSITORY"]
TOKEN = os.environ["GH_TOKEN"]
EDITOR = os.environ.get("EDITOR_LOGIN", "someone")
MARK = "<!-- generated by site/learn_export.py"
ROOT = Path.cwd()
SEED = ROOT / "wiki"
LESSONS = ROOT / "site" / "content" / "learn" / "lessons"
MACHINE = ("Seed wiki from repository", "Rebuild scoreboard")


def run(*args: str, cwd: Path | None = None) -> str:
    return subprocess.run(args, cwd=cwd, check=True, capture_output=True, text=True).stdout.strip()


def source_of(page: str) -> str:
    """The file a generated page is made from."""
    for p in LESSONS.glob("*.md"):
        m = re.search(r"^wiki:\s*(\S+)\s*$", p.read_text(encoding="utf-8"), re.M)
        if m and m.group(1) == page:
            return p.relative_to(ROOT).as_posix()
    if page == "Start-Here":
        return "site/content/learn/start-here.md"
    return "site/content/learn/curriculum.py"   # a track page


def diff(before: str, after: str, name: str) -> str:
    d = "".join(difflib.unified_diff(before.splitlines(True), after.splitlines(True),
                                     f"wiki/{name}.md (repository)", f"{name} (live wiki)", n=2))
    return d if len(d) < 12000 else d[:12000] + "\n… (diff truncated; the full page is on the wiki)\n"


def issue(title: str, body: str) -> None:
    found = run("gh", "issue", "list", "--repo", REPO, "--state", "open", "--search", f"in:title {title}",
                "--json", "number,title", "--jq", f".[] | select(.title == {json.dumps(title)}) | .number")
    if found:
        run("gh", "issue", "comment", found.splitlines()[0], "--repo", REPO, "--body", body)
        print(f"commented on #{found.splitlines()[0]}: {title}")
    else:
        print(run("gh", "issue", "create", "--repo", REPO, "--title", title, "--body", body,
                  "--label", "documentation"))


def main() -> int:
    pages = json.loads(os.environ.get("PAGES") or "[]")
    live = ROOT / "wiki-live"
    run("git", "clone", "--quiet", f"https://x-access-token:{TOKEN}@github.com/{REPO}.wiki.git", str(live))
    handwritten: list[tuple[str, str, str]] = []
    for pg in pages:
        name = pg.get("page_name") or ""
        f = live / f"{name}.md"
        if not name or name == "Scoreboard" or not f.exists():
            continue
        last = run("git", "log", "-1", "--format=%s", "--", f.name, cwd=live)
        if last.startswith(MACHINE):
            print(f"{name}: last written by a sync, not a person")
            continue
        now = f.read_text(encoding="utf-8")
        seeded = SEED / f"{name}.md"
        before = seeded.read_text(encoding="utf-8") if seeded.exists() else ""
        if now == before:
            print(f"{name}: already in wiki/")
            continue
        url = pg.get("html_url") or f"https://github.com/{REPO}/wiki/{name}"
        if now.startswith(MARK) or before.startswith(MARK):
            src = source_of(name)
            issue(f"Wiki edit to a generated page: {name}",
                  f"@{EDITOR} edited [{name}]({url}) on the wiki. That page is generated from "
                  f"[`{src}`](https://github.com/{REPO}/blob/main/{src}), so the next "
                  f"`python3 site/learn_export.py` would replace it and the edit would be lost.\n\n"
                  f"**To keep it:** make the same change in `{src}`, run the exporter, commit, and sync. "
                  f"`wiki/sync.sh` will refuse to overwrite the page until then.\n\n"
                  f"```diff\n{diff(before, now, name)}```")
        else:
            handwritten.append((name, url, diff(before, now, name)))
    if not handwritten:
        return 0
    sha = (pages[0].get("sha") or "edit")[:7]
    branch = f"wiki-edit/{handwritten[0][0][:40]}-{sha}"
    run("git", "config", "user.name", "github-actions[bot]")
    run("git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com")
    run("git", "checkout", "-q", "-b", branch)
    for name, _, _ in handwritten:
        (SEED / f"{name}.md").write_text((live / f"{name}.md").read_text(encoding="utf-8"), encoding="utf-8")
        run("git", "add", f"wiki/{name}.md")
    names = ", ".join(n for n, _, _ in handwritten)
    run("git", "commit", "-q", "-m", f"Bring wiki edits home: {names}", "-m", f"Edited on the wiki by @{EDITOR}.")
    run("git", "push", "-q", "origin", branch)
    compare = f"https://github.com/{REPO}/compare/main...{branch}?expand=1"
    blocks = "\n\n".join(f"**[{n}]({u})**\n\n```diff\n{d}```" for n, u, d in handwritten)
    issue(f"Wiki edits to bring home: {names}",
          f"@{EDITOR} edited {len(handwritten)} hand-written page(s) on the wiki. The edit is on branch "
          f"`{branch}`: **[open the pull request]({compare})** and merge it, so `wiki/` has it and the next "
          f"`wiki/sync.sh` keeps it rather than refusing to run.\n\n{blocks}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
