#!/usr/bin/env python3
"""Put the course companion on the wiki: one page per module, a hub, and a labs page.

    python3 site/course_export.py          # then: python3 wiki/check.py --strict && bash wiki/sync.sh

The source is modules/*/README.md, modules/README.md, labs/README.md, labs/catalog/*/*/lab.toml and
docs/learning-paths/README.md. The repository is canonical; these pages are the reading order, with
every link made absolute, plus what the repository cannot say: which tutorial lesson frames each
module, which playbook tool exercises it, and where its errors are collected. Every generated page
starts with a marker, and the exporter refuses to overwrite a page that does not carry it. The sidebar
keeps everything outside its marked course block.
"""
from __future__ import annotations

import posixpath
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
ROOT = SITE.parent
sys.path.insert(0, str(SITE))
from pages import learn  # noqa: E402

WIKI = ROOT / "wiki"
MODULES = ROOT / "modules"
LABS = ROOT / "labs"
REPO = learn.REPO
BLOB, TREE = f"{REPO}/blob/main/", f"{REPO}/tree/main/"
SIM = f"{learn.BASE_URL}simulator/"
MARK = "<!-- generated by site/course_export.py from modules/ and labs/ — edit the source, not this page -->"
BLOCK = re.compile(r"<!-- course:start[^>]*-->[\s\S]*?<!-- course:end -->\n?")

# The five tracks of the curriculum, as modules/README.md draws them.
TRACKS = [("Think", "00", "01"), ("Invoke", "02", "04"), ("Build", "05", "09"),
          ("Ground", "10", "10"), ("Ship", "11", "14"), ("Product · parallel", "15", "15")]

# What the repository cannot say about a module: the tutorial lesson that frames it, why, and the
# playbook tool that exercises the same decision. Lesson slugs are checked against the curriculum.
FRAME = {
    "00": ("p0-frame", "the phase this module's decision tools belong to", "toolkit/aifit", "the AI-fit assessor"),
    "01": ("what-is-the-agentic-pdlc", "why software with a model in it needs a different lifecycle", "", ""),
    "02": ("ai-agent-costs", "what a token actually costs once the habits are counted", "toolkit/leaks", "the bill leak calculator"),
    "03": ("p1-design-and-spec", "what a spec an agent can build looks like, before the console", "toolkit/autonomy", "the autonomy decision record"),
    "04": ("ai-guardrails-that-hold", "which controls hold and which are only prompts", "toolkit/gates", "the authority and gate mapper"),
    "05": ("p2-build-and-prove", "building in proven slices, which is what the loop makes possible", "toolkit/bolts", "the sprint-to-bolt planner"),
    "06": ("agentic-pdlc-for-engineers", "the engineer's own steps, where tools and memory get their contracts", "", ""),
    "07": ("agentic-pdlc-for-solution-architects", "how many agents, and why each hand-off costs", "toolkit/utree", "the NFR utility tree"),
    "08": ("one-lifecycle-for-every-method", "why the framework changes and the lifecycle does not", "", ""),
    "09": ("ai-agent-costs", "context is the largest line on the bill", "toolkit/cache", "the cache break-even calculator"),
    "10": ("prove-ai-accuracy", "the evaluation gate retrieval has to pass", "toolkit/bar", "the acceptance bar calculator"),
    "11": ("p3-run-and-learn", "what running an agent as a service asks of the team", "toolkit/report", "the two-number report builder"),
    "12": ("p1-design-and-spec", "an interface between agents is a spec, and it has the same gate", "", ""),
    "13": ("agentic-pdlc-for-qa", "testing software that is right a share of the time", "toolkit/confidence", "the golden-set confidence calculator"),
    "14": ("shadow-mode-and-cutover", "shadow, canary and cut-over, with the evidence each needs", "toolkit/cutover", "the cut-over evidence calculator"),
    "15": ("agentic-pdlc-for-product-managers", "the product manager's eight steps, which this module practises", "toolkit/value", "the value line calculator"),
}


# ------------------------------------------------------------------------------------------ helpers
def strip_emoji(s: str) -> str:
    return re.sub(r"^[^\w\[]+", "", s).strip()


def page_name(title: str) -> str:
    """'🔁 Module 05 · The Agent Loop: No Framework to Strands' -> 'Module-05-The-Agent-Loop-No-Framework-to-Strands'."""
    t = strip_emoji(title)
    t = re.sub(r"[^A-Za-z0-9]+", "-", t).strip("-")
    return t


def sections(md: str) -> tuple[str, dict[str, str]]:
    """The text before the first ``## `` heading, and each ``## `` section's body, in order."""
    parts = re.split(r"^## (.+)$", md, flags=re.M)
    head, rest = parts[0], parts[1:]
    body = {}
    for i in range(0, len(rest), 2):
        body[rest[i].strip()] = rest[i + 1].strip("\n")
    return head, body


def absolute(md: str, base: str) -> str:
    """Rewrite every relative link in ``md`` to the repository, with blob for files and tree for folders."""
    def one(m: re.Match) -> str:
        text, href = m.group(1), m.group(2)
        if href.startswith(("http://", "https://", "mailto:", "#")):
            return m.group(0)
        path, _, frag = href.partition("#")
        full = posixpath.normpath(posixpath.join(base, path)) if path else base.rstrip("/")
        target = ROOT / full
        kind = TREE if target.is_dir() or path.endswith("/") else BLOB
        return f"[{text}]({kind}{full}{'#' + frag if frag else ''})"
    return re.sub(r"\[([^\]]*)\]\(([^)\s]+)\)", one, md)


def wiki_link(page: str, text: str) -> str:
    return f"[{text}]({page})"


def write(path: Path, text: str) -> None:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARK):
        sys.exit(f"refusing to overwrite hand-written wiki page {path.name}")
    path.write_text(text, encoding="utf-8")


def put_block(path: Path, block: str, after: str) -> None:
    text = path.read_text(encoding="utf-8")
    if BLOCK.search(text):
        text = BLOCK.sub(block, text, count=1)
    elif after in text:
        i = text.index(after) + len(after)
        text = text[:i] + "\n\n" + block + text[i:].lstrip("\n")
    else:
        sys.exit(f"{path.name}: no course block and no '{after}' to put one after")
    path.write_text(text, encoding="utf-8")


# ------------------------------------------------------------------------------------------ modules
class Module:
    def __init__(self, d: Path):
        self.dir = d
        self.num = d.name[:2]
        md = (d / "README.md").read_text(encoding="utf-8")
        self.title = re.search(r"^# (.+)$", md, re.M).group(1).strip()
        self.name = strip_emoji(self.title).split("·", 1)[1].strip()       # after "Module NN ·"
        self.page = page_name(self.title)
        head, self.secs = sections(md)
        m = re.search(r"^> (.+)$", head, re.M)
        self.tagline = m.group(1).strip() if m else ""
        m = re.search(r"\*\*Estimated time:\*\* (.+?) &nbsp;·&nbsp; \*\*Prerequisites:\*\* (.+)$", head, re.M)
        self.time, self.prereq = (m.group(1).strip(), m.group(2).strip()) if m else ("", "")
        # the paragraph(s) between the meta line and the rule
        intro = head[m.end():] if m else head
        intro = intro.split("\n---", 1)[0]
        self.intro = "\n".join(l for l in intro.strip().splitlines() if not l.startswith("<")).strip()
        self.base = f"modules/{d.name}/"
        self.track = next(name for name, lo, hi in TRACKS if lo <= self.num <= hi)

    def section(self, name: str) -> str:
        return absolute(self.secs.get(name, ""), self.base)


def load_modules() -> list[Module]:
    return [Module(d) for d in sorted(MODULES.iterdir()) if d.is_dir() and re.match(r"\d\d-", d.name)]


def module_page(m: Module, mods: list[Module], lessons: dict) -> str:
    k = mods.index(m)
    prev = mods[k - 1] if k else None
    nxt = mods[k + 1] if k + 1 < len(mods) else None
    slug, why, tool, tool_name = FRAME[m.num]
    les = lessons[slug]
    play = f" Then try **[{tool_name}]({SIM}#/{tool})** in the playbook: the same decision, with your numbers." if tool else ""
    field = m.section("Field guide for this module").split("\n---", 1)[0].strip()
    field = re.sub(r"^Reference material for the ideas in this module[^\n]*\n+", "", field)
    artefact = m.section("Project artefact")
    steps = m.section("Run it in this order")
    nav = " · ".join(x for x in [
        f"[← {strip_emoji(prev.title)}]({prev.page})" if prev else "",
        "**[All modules](Course-Companion)**",
        f"[{strip_emoji(nxt.title)} →]({nxt.page})" if nxt else "**[Prove it in the labs →](Labs-Companion)**"] if x)
    return f"""{MARK}
# {m.title}

> {m.tagline}

**Module {m.num} of {len(mods):02d}** · track *{m.track}* · **Estimated time:** {m.time} · **Prerequisites:** {m.prereq}

{m.intro}

**[Open the module on GitHub ↗]({TREE}{m.base})**: the slides, notebooks, exercises and solutions are there. This page is the reading order, with the tutorial and the playbook alongside.

## Read first, on the site

The lesson that frames this module is **[{les.title}]({les.url})** ({learn.minutes(les.body)} min): {why}.{play}

## What you will be able to do

{m.section("What you will be able to do")}

## Concepts in this module

{m.section("Concepts in this module")}

## Run it in this order

{steps}

{m.section("Solutions")}
{f'''
## Project artefact

{artefact}
''' if artefact else ''}
## Common mistakes

{m.section("Common mistakes")}

## When it breaks

Every error anyone has hit in this course is in the **[Error Index](Error-Index)**, by the exact string. Model access and region problems are in [Model and Region Notes](Model-and-Region-Notes). If it is a question rather than an error, check the [answered ones](Community-Answers) first, then ask in [Q&A]({REPO}/discussions/categories/q-a).

## Field guide for this module

{field}

---

{nav}

<sub>✏️ This page is generated from [`{m.base}README.md`]({BLOB}{m.base}README.md). To change it, [edit the module README]({REPO}/edit/main/{m.base}README.md): an edit made here is replaced at the next sync.</sub>
"""


# --------------------------------------------------------------------------------------------- labs
def labs_page(mods: list[Module]) -> str:
    md = (LABS / "README.md").read_text(encoding="utf-8")
    head, secs = sections(md)
    phases = re.search(r"\| \| Phase \| What happens \|[\s\S]*?(?=\n\n)", secs.get("Why this exists", "")).group(0)
    start = re.search(r"```bash\n[\s\S]*?```", secs.get("Start in 60 seconds", "")).group(0)
    catalog = re.search(r"<!-- LABS:START -->\n([\s\S]*?)<!-- LABS:END -->", secs.get("The catalog", "")).group(1).strip()
    catalog = absolute(catalog, "labs/")
    three = absolute(re.search(r"\| \| Setup \| You get \|[\s\S]*?(?=\n\n)", secs.get("Three ways to run a lab", "")).group(0), "labs/")
    drills = absolute(secs.get("Drills: the bite-sized sequence", "").split("\n\n")[0], "labs/")
    # which module teaches each lab, from the manifests
    by_page = {m.dir.name: m for m in mods}
    rows = []
    for toml in sorted(LABS.glob("catalog/*/*/lab.toml")):
        t = toml.read_text(encoding="utf-8")
        g = lambda k: (re.search(rf'^{k}\s*=\s*"([^"]*)"', t, re.M) or [None, ""])[1]
        mins = (re.search(r"^est_minutes\s*=\s*(\d+)", t, re.M) or [None, ""])[1]
        mod = by_page.get(g("module"))
        rows.append(f"| **[{g('id')}]({TREE}labs/{toml.parent.relative_to(LABS).as_posix()}/)** · {g('title')} | `{g('difficulty')}` | {mins} min | "
                    f"{wiki_link(mod.page, strip_emoji(mod.title)) if mod else '. '} |")
    return f"""{MARK}
# The labs companion

*The L.A.B. Simulator: Learn → Apply → Break. Auto-graded, decision-driven labs, every one offline and without an AWS account.*

**[Open the labs on GitHub ↗]({TREE}labs/)** · [the pathway]({BLOB}labs/PATHWAY.md) · [grade one in the Arena]({REPO}/discussions/75)

Each lab has three phases, and the Break phase is the point:

{phases}

## Start in 60 seconds

In Codespaces, [open one]({REPO.replace('github.com', 'codespaces.new')}?quickstart=1) and type `lab next`. Locally:

{start}

## The catalog

{catalog}

More labs are specified and open for contribution: the **[full pathway]({BLOB}labs/PATHWAY.md#the-complete-pathway)** is the 41-lab map, and [how to author one]({BLOB}labs/CONTRIBUTING-A-LAB.md) is the guide.

## Which module teaches each lab

| Lab | Difficulty | Time | Learn it in |
| --- | --- | --- | --- |
{chr(10).join(rows)}

## Drills, when you have ten minutes

{drills}

Post `/drill AGL-101` in the [Simulator Arena]({REPO}/discussions/75) and a bot grades it in the thread; progress lands on the [Scoreboard](Scoreboard).

## Three ways to run a lab

{three}

---

**[The course companion](Course-Companion)** · **[Teach it: the cohort kit](Cohort-Kit)** · [Exercises with answers](Exercises-and-Answers)

<sub>✏️ This page is generated from [`labs/README.md`]({BLOB}labs/README.md) and the lab manifests, an edit made here is replaced at the next sync.</sub>
"""


# ---------------------------------------------------------------------------------------------- hub
def hub_page(mods: list[Module], lessons: dict) -> str:
    paths_md = (ROOT / "docs/learning-paths/README.md").read_text(encoding="utf-8")
    paths = absolute(re.search(r"\| Path \| For \| Time \| Finish line \|[\s\S]*?(?=\n\n)", paths_md).group(0), "docs/learning-paths/")
    rules = absolute(re.search(r"## Ground rules that apply to every path\n\n([\s\S]*?)(?=\n## |\Z)", paths_md).group(1).strip(), "docs/learning-paths/")
    rows = []
    for m in mods:
        slug = FRAME[m.num][0]
        rows.append(f"| **{m.num}** | {m.track} | **{wiki_link(m.page, m.name)}**<br/><sub>{m.tagline}</sub> | {m.time} | [{lessons[slug].short}]({lessons[slug].url}) |")
    tracks = "\n".join(f"| **{name}** | {lo}–{hi} |" if lo != hi else f"| **{name}** | {lo} |" for name, lo, hi in TRACKS)
    total = len(mods)
    return f"""{MARK}
# The course companion

*Sixteen modules, five tracks, one rule: every abstraction is preceded by the thing it abstracts.*

The course lives in the repository, under [`modules/`]({TREE}modules/): slides, notebooks, exercises, workbooks and solutions, reviewed and versioned. These pages are the companion: one page per module with its reading order, the [tutorial]({learn.BASE_URL}learn/) lesson that frames it, the [playbook]({SIM}) tool that exercises the same decision, and where its errors and questions are collected. Read the module README first, always; this page tells you what to read around it.

**Where to start:** [START-HERE]({BLOB}docs/START-HERE.md) in the repository picks a path for you. Not sure? {wiki_link(mods[0].page, "Module 00")} needs no AWS account and no code.

## The five tracks

| Track | Modules |
| --- | --- |
{tracks}

You write the agent loop by hand before meeting a framework (05 → 06), build retrieval by hand before a managed knowledge base (10), and test before you deploy (13 → 14).

## All {total} modules

| # | Track | Module | Time | Read first |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Pick a path

Nobody needs all sixteen in the same order. Each path is a subset, in a sequence, with a finish line:

{paths}

{rules}

## Prove it, then teach it

- **[The labs companion](Labs-Companion)**: auto-graded labs that try to break your solution, and which module teaches each one.
- **[The cohort kit](Cohort-Kit)**: ninety-minute sessions that turn the tutorial and this course into a programme for a team.
- **[Study plans](Study-Plans)**: the same material fitted to a week, a weekend, four weeks of evenings or twelve weeks of reading group.

---

<sub>✏️ This page is generated from [`modules/README.md`]({BLOB}modules/README.md), the module READMEs and [`docs/learning-paths/README.md`]({BLOB}docs/learning-paths/README.md): an edit made here is replaced at the next sync.</sub>
"""


def sidebar_block(mods: list[Module]) -> str:
    items = "\n".join(f"{m.num}. [{m.name}]({m.page})" for m in mods)
    return ("<!-- course:start · generated by site/course_export.py -->\n"
            "**[The course companion](Course-Companion)** · **[Labs](Labs-Companion)**\n\n"
            f"<details><summary><b>The {len(mods)} modules</b></summary>\n\n{items}\n\n</details>\n"
            "<!-- course:end -->\n")


def main() -> int:
    _, tracks, lessons = learn.load()
    mods = load_modules()
    bad = [f"{n}: {s}" for n, (s, *_) in FRAME.items() if s not in lessons]
    if bad:
        sys.exit("FRAME names lessons that do not exist: " + ", ".join(bad))
    missing = [m.num for m in mods if m.num not in FRAME]
    if missing:
        sys.exit("FRAME has no entry for module(s) " + ", ".join(missing))
    for m in mods:
        for want in ("What you will be able to do", "Concepts in this module", "Run it in this order", "Solutions", "Common mistakes"):
            if want not in m.secs:
                sys.exit(f"{m.dir.name}/README.md has no '## {want}' section")
    written = []
    for m in mods:
        write(WIKI / f"{m.page}.md", module_page(m, mods, lessons))
        written.append(m.page)
    write(WIKI / "Course-Companion.md", hub_page(mods, lessons))
    write(WIKI / "Labs-Companion.md", labs_page(mods))
    written += ["Course-Companion", "Labs-Companion"]
    put_block(WIKI / "_Sidebar.md", sidebar_block(mods), after="### 📚 Course and labs")
    stale = [p for p in WIKI.glob("*.md") if p.stem not in written and p.read_text(encoding="utf-8").startswith(MARK)]
    for p in stale:
        p.unlink()
    print(f"wrote {len(written)} wiki pages; sidebar course block updated; {len(stale)} stale generated pages deleted")
    for p in stale:
        print(f"  deleted wiki/{p.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
