#!/usr/bin/env python3
"""Export the mental models to a wiki page, from the same data the site renders.

The site page carries the drawings; the wiki copy carries the words. The twelve models come from
``pages/models.py``, so a change to a model reaches both. The words written for the wiki page alone
(where each model bites, with its picture, and the three that get resisted) live in
``content/library/mental-models-wiki.md``, and the export puts them back byte for byte, so running it
never loses them. Each heading also keeps the anchor of the name it had before, so old links land.

    python3 site/export_models.py            # writes ../wiki/Mental-Models.md
    python3 site/export_models.py --check    # changes nothing; exits 1 with the diff if out of date
"""
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
sys.path.insert(0, str(SITE))
from pages import models as M  # noqa: E402

WIKI = SITE.parent / "wiki"
LIVE = "https://akash-coded.github.io/aws-bedrock-agentcore-strands/"
BLOB = "https://github.com/akash-coded/aws-bedrock-agentcore-strands/blob/main/"
KEPT = SITE / "content" / "library" / "mental-models-wiki.md"
MARK = ("<!-- generated by site/export_models.py from site/pages/models.py and "
        "site/content/library/mental-models-wiki.md: edit the sources, not this page -->")
# A line of its own in KEPT: the block under it goes after the index, or at the end of one model.
PLACE = re.compile(r"^<!--[ \t]*after:[ \t]*([A-Za-z0-9_-]+)[ \t]*-->[ \t]*$", re.M)

# The names the models carried until the site rewrote them for readers (25 September 2026). Lessons,
# the live site and bookmarks link to these anchors, so each heading keeps its old one as well.
FORMER = {
    "length": "Length is the enemy",
    "doors": "Reversibility is the hinge",
    "lever": "A hold is a lever, not a brake",
    "boundary": "A prompt is a request; a signature is a boundary",
    "average": "The average hides the slice that matters",
    "bound": "A score is not proof",
    "speed": "Evidence arrives at the speed of traffic",
    "habits": "Cost is a product of habits",
    "fanout": "Parallelism is a property of a tool, not a headcount",
    "depth": "Depth is a dial, not a constant",
    "artefact": "A phase ends on an artefact, not a date",
    "drift": "Drift is the defect with no error message",
}


def clean(s: str) -> str:
    """The site content carries a little inline HTML; the wiki wants markdown."""
    s = re.sub(r"</?em>", "*", s)
    s = re.sub(r"</?strong>", "**", s)
    s = re.sub(r"<code>([^<]*)</code>", r"`\1`", s)
    return re.sub(r"\s+", " ", s).strip()


def link(label: str, href: str) -> str:
    if href.startswith("http"):
        return f"[{label}]({href})"
    return f"[{label}]({LIVE}{href.lstrip('./')})"


def slug(heading: str) -> str:
    """GitHub's anchor for a heading, by the rule wiki/check.py checks links against."""
    s = re.sub(r"<[^>]+>", "", heading)
    return re.sub(r"[^a-z0-9 -]", "", s.lower()).strip().replace(" ", "-")


def drawn(words: str) -> str:
    """A picture keeps only its two marker lines in the source: draw it as wiki_pictures.py does."""
    import wiki_pictures as WP
    return WP.BLOCK.sub(lambda m: WP.picture(m.group(1)), words).strip("\n")


def kept() -> dict[str, str]:
    """The words written for the wiki page alone, by where they go: ``index``, or a model's id."""
    if not KEPT.exists():
        sys.exit(f"{KEPT} is missing: it holds words the wiki page must not lose")
    text = KEPT.read_text(encoding="utf-8")
    for line in text.splitlines():
        if re.search(r"<!--[^>]*\bafter\b", line) and not PLACE.match(line):
            sys.exit(f"{KEPT.name}: {line!r} looks like a marker but is not one, so its words would be lost")
    places = {"index"} | {m["id"] for m in M.MODELS}
    parts = PLACE.split(text)
    out: dict[str, str] = {}
    for where, words in zip(parts[1::2], parts[2::2]):
        if where not in places:
            sys.exit(f"{KEPT.name}: nowhere called {where!r}; a block goes after 'index' or a model's id")
        if where in out:
            sys.exit(f"{KEPT.name}: two blocks go after {where!r}")
        if words.strip():
            out[where] = drawn(words.strip("\n"))
    return out


def page(keep: dict[str, str]) -> str:
    stale = sorted(set(FORMER) - {m["id"] for m in M.MODELS})
    if stale:
        sys.exit(f"FORMER names models the site no longer has: {', '.join(stale)}; their old anchors would go")
    L = [MARK, "# Mental models", "",
         "**Twelve shapes that make the rest of this manual predictable.**", "",
         "A procedure tells you what to do on Tuesday. A model tells you what to expect before you "
         "start, which is what lets somebody make a good call on a case this manual never covered.",
         "",
         f"Each one below is the model, what it predicts, the mistake it prevents, the part that is "
         f"easy to miss, and a test for whether it has landed. The [illustrated version]({LIVE}models/) "
         f"draws each one; this copy is the reading text.", "",
         "---", "", "## The twelve", "",
         "| # | Model | In one line |", "| --- | --- | --- |"]
    for i, m in enumerate(M.MODELS, 1):
        L.append(f"| {i} | [**{m['name']}**](#{slug(m['name'])}) | {clean(m['one'])} |")
    L += ["", "---", ""]
    if "index" in keep:
        L += [keep["index"], "", "---", ""]
    for m in M.MODELS:
        was = f'<a name="{slug(FORMER[m["id"]])}"></a>' if m["id"] in FORMER else ""
        L += [f"## {was}{m['name']}", "",
              f"> {clean(m['one'])}", "",
              f"**What it predicts.** {clean(m['predicts'])}", "",
              f"**The mistake it prevents.** {clean(m['prevents'])}", "",
              f"**The part that is easy to miss.** {clean(m['subtle'])}", "",
              f"**Landed when:** {clean(m['landed'])}", "",
              "Where you meet it: " + " · ".join(link(l, h) for l, h in m["where"]), ""]
        if m["id"] in keep:
            L += [keep[m["id"]], ""]
        L += ["---", ""]
    L += ["## How to use these", "",
          "1. **Teach one a week, not twelve at once.** A model lands when somebody uses it "
          "unprompted in an argument, which takes a fortnight of availability rather than an hour "
          "of exposure.",
          "2. **Use the landed-when line as the test.** Not whether the team can define it, but "
          "whether the question it implies has started appearing in reviews.",
          "3. **Expect three to be resisted.** Usually the hold as a lever, the average hiding the "
          "slice, and depth as a dial, because each contradicts something a competent person "
          "currently believes is good practice.",
          "4. **Pair each with its arithmetic once.** The intuition is what you carry; the formula "
          "is what settles the argument. See [Formulas and Calculators](Formulas-and-Calculators).",
          "5. **Keep the subtlety visible.** A model applied past its boundary does more damage "
          "than no model, because it arrives with confidence.", "",
          "---", "",
          "**Next:** [Decision Trees](Decision-Trees) · [Formulas and Calculators](Formulas-and-Calculators) "
          "· [Anti-Patterns](Anti-Patterns) · [The Agentic PDLC](The-Agentic-PDLC)", "",
          f"<sub>✏️ This page is generated from [`site/pages/models.py`]({BLOB}site/pages/models.py), "
          f"the twelve models, and [`site/content/library/mental-models-wiki.md`]({BLOB}"
          f"site/content/library/mental-models-wiki.md), the words written for this page alone: an edit "
          f"made here is replaced at the next sync.</sub>", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 and print the diff if the page is out of date")
    args = ap.parse_args()
    out = WIKI / "Mental-Models.md"
    keep = kept()
    text = page(keep)
    if args.check:
        now = out.read_text(encoding="utf-8") if out.exists() else ""
        if now == text:
            print(f"{out.name} is up to date")
            return 0
        sys.stdout.writelines(difflib.unified_diff(now.splitlines(True), text.splitlines(True),
                                                   f"wiki/{out.name}", "regenerated"))
        print(f"\n{out.name} is out of date: run python3 site/export_models.py")
        return 1
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out.name}: {len(M.MODELS)} models, {len(keep)} kept block(s), "
          f"{len(text.encode('utf-8')):,} bytes, {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
