#!/usr/bin/env python3
"""Put the tutorial's index on the wiki: a Start Here page, one short page per track, and the
tutorial blocks at the top of the sidebar and Home. The lessons themselves live on the site only.

    python3 site/wiki_export.py           # the Journey pages, if the roles changed
    python3 site/learn_export.py          # then: python3 wiki/check.py --strict && bash wiki/sync.sh

The source is site/content/learn/. The site copy is canonical and indexed; the wiki keeps a thin index
so a reader who lives on GitHub can still find every lesson in order, and so the reference pages can
point at the lesson that teaches them. Every generated page starts with a marker, and the exporter
refuses to overwrite any wiki page that does not carry it. Generated pages whose source is gone (the
55 full lesson mirrors, since 2026-09-24) are deleted, and named.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
sys.path.insert(0, str(SITE))
from pages import learn  # noqa: E402

WIKI = SITE.parent / "wiki"
MARK = "<!-- generated by site/learn_export.py from site/content/learn — edit the source, not this page -->"
BLOCK = re.compile(r"<!-- tutorial:start[^>]*-->[\s\S]*?<!-- tutorial:end -->\n?")


def picture(key: str, les_url: str, reg: dict) -> str:
    name = learn.shot_name(key)
    alt = reg[key]["alt"].replace('"', "&quot;")
    return (f'<p align="center"><a href="{les_url}"><picture>'
            f'<source media="(prefers-color-scheme: dark)" srcset="{learn.SHOTS}{name}.dark.webp">'
            f'<img alt="{alt}" src="{learn.SHOTS}{name}.light.webp" width="{"440" if key.startswith("model:") else "100%"}">'
            f"</picture></a></p>\n\n<sub>▸ <a href=\"{les_url}\">Open the live, interactive version</a></sub>")


def body_for_wiki(md: str, link, les_url: str, reg: dict) -> str:
    out = []
    for line in md.splitlines():
        d = learn.DIRECTIVE.match(line.strip())
        out.append(picture(f"{d.group(1)}:{d.group(2)}", les_url, reg) if d else line)
    text = "\n".join(out)
    # a screenshot on its own line: markdown has no width, and GitHub would stretch a narrow one
    def shot(m):
        size = learn.image_size(m.group(2))
        if not size:
            return m.group(0)
        alt = m.group(1).replace('"', "&quot;")
        return f'<p align="center"><img alt="{alt}" src="{link(m.group(2))}" width="{size[0]}"></p>'
    text = re.sub(r"^!\[([^\]]*)\]\((site:assets/[^)\s]+)\)\s*$", shot, text, flags=re.M)
    # resolve the tutorial's link schemes; leave fenced blocks alone
    parts = re.split(r"(```[\s\S]*?```)", text)
    for i in range(0, len(parts), 2):
        parts[i] = re.sub(r"\]\(((?:lesson|track|wiki|site|repo|sim):[^)\s]*)\)",
                          lambda m: "](" + link(m.group(1)) + ")", parts[i])
    return "".join(parts)


# Cohort sessions (hand-written) that teach each track; a track page links to its sessions when they exist.
SESSIONS = {
    "getting-started": [("Cohort-Session-1-Kick-off", "Session 1 · Kick-off")],
    "fundamentals": [("Cohort-Session-1-Kick-off", "Session 1 · Kick-off"),
                     ("Cohort-Session-2-Frame-and-Spec", "Session 2 · Frame and spec"),
                     ("Cohort-Session-3-Build-Run-and-Loops", "Session 3 · Build, run and the loops")],
    "methods": [("Cohort-Session-4-Methods-Decoded", "Session 4 · Methods decoded")],
    "delivery": [("Cohort-Session-5-Plan-and-Review", "Session 5 · Plan and review"),
                 ("Cohort-Session-6-Prove-and-Ship", "Session 6 · Prove and ship"),
                 ("Cohort-Session-7-Govern-and-Scale", "Session 7 · Govern and scale")],
    "roles": [("Cohort-Session-8-Practice-and-Roles", "Session 8 · Practice and roles")],
    "organisation": [("Cohort-Session-7-Govern-and-Scale", "Session 7 · Govern and scale")],
    "practice": [("Cohort-Session-8-Practice-and-Roles", "Session 8 · Practice and roles")],
    "interviews": [("Cohort-Session-8-Practice-and-Roles", "Session 8 · Practice and roles")],
}


def track_page(t, tracks) -> str:
    k = tracks.index(t)
    rows = "\n".join(f"| {l.n} | **[{l.title}]({l.url})** | {l.description} | {learn.minutes(l.body)} min |"
                     for l in t.lessons)
    total = sum(learn.minutes(l.body) for l in t.lessons)
    prev = tracks[k - 1] if k else None
    nxt = tracks[k + 1] if k + 1 < len(tracks) else None
    steps = " · ".join(x for x in [f"[← {prev.title}]({prev.wiki})" if prev else "",
                                   "**[All tracks](Start-Here)**",
                                   f"[{nxt.title} →]({nxt.wiki})" if nxt else ""] if x)
    sessions = [(page, name) for page, name in SESSIONS.get(t.id, []) if (WIKI / f"{page}.md").exists()]
    teach = ("\n\n**Teaching it?** " + " · ".join(f"[{name}]({page})" for page, name in sessions)
             + " in the [Cohort Kit](Cohort-Kit) turn this track into ninety-minute sessions." if sessions else "")
    return f"""{MARK}
# {t.title}

{t.blurb}

**{len(t.lessons)} lessons · about {total} minutes** · {t.promise}

Every lesson opens on the site, where the pictures are live and the text is searchable:
**[start this track ↗]({t.url})**, or pick a lesson.

| # | Lesson | What it covers | Time |
| --- | --- | --- | --- |
{rows}

{steps}{teach}

<sub>✏️ This page is generated from [`site/content/learn/curriculum.py`]({learn.REPO}/blob/main/site/content/learn/curriculum.py) — an edit made here is replaced at the next sync.</sub>
"""


def contents(tracks) -> str:
    """The whole curriculum as one table of contents, mysqltutorial-style."""
    blocks = []
    for k, t in enumerate(tracks, 1):
        total = sum(learn.minutes(l.body) for l in t.lessons)
        items = "\n".join(f"{l.n}. **[{l.title}]({l.url})** — {learn.minutes(l.body)} min" for l in t.lessons)
        blocks.append(f"### {k} · [{t.title}]({t.wiki})\n\n*{t.blurb}* — {len(t.lessons)} lessons, "
                      f"about {total} minutes.\n\n{items}")
    return "\n\n".join(blocks)


def start_page(lessons, tracks, reg) -> str:
    smeta, sbody = learn._front((learn.LEARN / "start-here.md").read_text(encoding="utf-8"), "start-here.md")
    link = learn.Links("wiki", lessons, tracks)
    start_url = f"{learn.BASE_URL}learn/"
    body = body_for_wiki(sbody, link, start_url, reg)
    n = sum(len(t.lessons) for t in tracks)
    return f"""{MARK}
# {smeta['title']}

*{smeta['dek']}*

**Free · {n} lessons · by {learn.AUTHOR}** · [Read it on the site, with live diagrams ↗]({start_url})

{body}

## Every lesson, in order

{contents(tracks)}

---

**Also here:** the playbook's full reference — [The Agentic PDLC](The-Agentic-PDLC), [the role pages](Role-Product-Manager),
[the journeys](Journey-Product-Manager), [the how-tos](How-to-Prove-the-Bar), [Formulas](Formulas-and-Calculators)
and [the Glossary](Playbook-Glossary). Every lesson links into them where you need the depth.

<sub>✏️ This page is generated from [`site/content/learn/start-here.md`]({learn.REPO}/blob/main/site/content/learn/start-here.md) — an edit made here is replaced at the next sync.</sub>
"""


def sidebar_block(tracks) -> str:
    n = sum(len(t.lessons) for t in tracks)
    items = "\n".join(f"{k}. [{t.title}]({t.wiki}) · {len(t.lessons)}" for k, t in enumerate(tracks, 1))
    return ("<!-- tutorial:start · generated by site/learn_export.py -->\n"
            "### 📘 The tutorial\n\n"
            f"**[▶ Start here](Start-Here)** · {n} lessons, [on the site ↗]({learn.BASE_URL}learn/)\n\n"
            f"{items}\n\n---\n<!-- tutorial:end -->\n")


def home_block(tracks) -> str:
    n = sum(len(t.lessons) for t in tracks)
    rows = "\n".join(f"| **[{t.title}]({t.wiki})** | {t.blurb} | {len(t.lessons)} |" for t in tracks)
    first = tracks[0].lessons[0]
    return f"""<!-- tutorial:start · generated by site/learn_export.py -->
# Learn the agentic PDLC

A free tutorial in short lessons on running software projects where an AI model does part of the
work — the four phases, the one hard gate and the eight loops; how AWS AI-DLC, AIDD, the BMAD Method
and spec-driven development fit onto them; what changes for each role, from engineer to executive;
how an organisation adopts it; a ninety-day case with twelve exercises; and interview question banks
with strong answers for AI product managers, forward deployed engineers, GenAI, agentic and AWS roles.
Each lesson opens with the answer, carries a picture, ends with how to apply it in your role, and
credits its sources.

**[▶ Start here](Start-Here)** · or go straight to **[{first.title}]({first.url})**

| Track | What it covers | Lessons |
| --- | --- | --- |
{rows}

*{n} lessons so far.* The lessons live on the site, with live diagrams: [akash-coded.github.io/…/learn]({learn.BASE_URL}learn/). The wiki keeps this index, the reference pages, the [course companion](Course-Companion) and the [cohort kit](Cohort-Kit).

---

<!-- tutorial:end -->
"""


# Hand-written reference pages, each with the lesson that teaches it in one sitting. The exporter keeps
# one marked line under each page's title, and never touches anything else on the page. The Journey
# pages are rewritten by site/wiki_export.py, so run that first and this after it.
LEARN_IT = "concept"   # the lesson is the introduction; the page is the reference
SHORT = "role"         # the lesson is the short version of a long page
POINTERS = {
    "The-Agentic-PDLC": ("what-is-the-agentic-pdlc", LEARN_IT),
    "The-Eight-Loops": ("the-eight-loops", LEARN_IT),
    "The-Evidence-Pack": ("the-evidence-pack", LEARN_IT),
    "Gates-and-Governance": ("ai-governance-gates", LEARN_IT),
    "Anti-Patterns": ("why-agentic-ai-projects-fail", LEARN_IT),
    "How-to-Control-the-Token-Bill": ("ai-agent-costs", LEARN_IT),
    "How-to-Cut-Sprints-into-Bolts": ("bolts-vs-sprints", LEARN_IT),
    "How-to-Design-an-Agent-on-Paper": ("p1-design-and-spec", LEARN_IT),
    "How-to-Hold-the-Security-Boundary": ("ai-guardrails-that-hold", LEARN_IT),
    "How-to-Prove-the-Bar": ("prove-ai-accuracy", LEARN_IT),
    "How-to-Review-by-Risk-Band": ("review-ai-generated-code", LEARN_IT),
    "How-to-Run-a-Missing-Control-Postmortem": ("ai-incident-postmortem", LEARN_IT),
    "Role-Product-Manager": ("agentic-pdlc-for-product-managers", SHORT),
    "Role-Solution-Architect": ("agentic-pdlc-for-solution-architects", SHORT),
    "Role-Engineering-Lead": ("agentic-pdlc-for-engineers", SHORT),
    "Role-QA-Lead": ("agentic-pdlc-for-qa", SHORT),
    "Role-DevOps": ("agentic-pdlc-for-devops", SHORT),
    "Role-Sponsor": ("agentic-pdlc-for-business-sponsors", SHORT),
    "Journey-Product-Manager": ("agentic-pdlc-for-product-managers", SHORT),
    "Journey-Solution-Architect": ("agentic-pdlc-for-solution-architects", SHORT),
    "Journey-Engineering-Lead": ("agentic-pdlc-for-engineers", SHORT),
    "Journey-QA-Lead": ("agentic-pdlc-for-qa", SHORT),
    "Journey-DevOps": ("agentic-pdlc-for-devops", SHORT),
    "Exercises-and-Answers": ("agentic-pdlc-exercises", "exercises"),
    "Formulas-and-Calculators": ("agentic-pdlc-exercises", "formulas"),
}
POINTER = re.compile(r"\n\n<!-- tutorial:lesson -->[^\n]*<!-- /tutorial:lesson -->(?=\n)")


def pointer_line(les, kind: str) -> str:
    to = f"**[{les.short}]({les.url})**"
    say = {
        LEARN_IT: f"New to this? Start with the lesson {to} — the idea step by step, with a worked "
                  f"problem. This page is the reference.",
        SHORT: f"The short version is the lesson {to} — the whole role in one sitting. This page goes deeper.",
        "exercises": f"Twelve more, three per phase, are in the lesson {to}, each with its working.",
        "formulas": f"To practise these, the lesson {to} applies them in the order a project needs them.",
    }[kind]
    return f"<!-- tutorial:lesson -->*{say}*<!-- /tutorial:lesson -->"


def put_pointer(path: Path, line: str) -> None:
    text = path.read_text(encoding="utf-8")
    if text.startswith(MARK):
        sys.exit(f"{path.name} is generated; a pointer belongs on a hand-written page")
    text = POINTER.sub("", text)
    m = re.search(r"^# .*$", text, re.M)
    if not m:
        sys.exit(f"{path.name} has no title to put the lesson pointer under")
    path.write_text(text[:m.end()] + "\n\n" + line + text[m.end():], encoding="utf-8")


def put_block(path: Path, block: str, after: str | None = None) -> None:
    text = path.read_text(encoding="utf-8")
    if BLOCK.search(text):
        text = BLOCK.sub(block, text, count=1)
    elif after and after in text:
        i = text.index(after) + len(after)
        text = text[:i] + "\n\n" + block + text[i:].lstrip("\n")
    else:
        text = block + "\n" + text
    path.write_text(text, encoding="utf-8")


def write(path: Path, text: str) -> None:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARK):
        sys.exit(f"refusing to overwrite hand-written wiki page {path.name}")
    path.write_text(text, encoding="utf-8")


def main() -> int:
    meta, tracks, lessons = learn.load()
    errors, _ = learn.validate(meta, tracks, lessons)
    if errors:
        sys.exit("fix the lessons first (python3 site/build.py shows why):\n  " + "\n  ".join(errors))
    reg = learn._visuals()
    missing = [k for k in learn.used_visuals()
               if not (SITE / "assets" / "learn" / f"{learn.shot_name(k)}.light.webp").exists()]
    if missing:
        sys.exit("screenshots missing for " + ", ".join(missing) + " — run site/tools/shoot.mjs")
    written = []
    for t in tracks:
        write(WIKI / f"{t.wiki}.md", track_page(t, tracks))
        written.append(t.wiki)
    write(WIKI / "Start-Here.md", start_page(lessons, tracks, reg))
    written.append("Start-Here")
    put_block(WIKI / "_Sidebar.md", sidebar_block(tracks), after="**[🏠 Wiki Home](Home)**")
    put_block(WIKI / "Home.md", home_block(tracks))
    by_slug = {les.slug: les for t in tracks for les in t.lessons}
    for page, (slug, kind) in POINTERS.items():
        put_pointer(WIKI / f"{page}.md", pointer_line(by_slug[slug], kind))
    # a generated page whose source is gone (a renamed track, or the old per-lesson mirrors) is deleted:
    # only pages carrying this exporter's marker qualify, so a hand-written page is never touched
    stale = [p for p in WIKI.glob("*.md") if p.stem not in written
             and p.read_text(encoding="utf-8").startswith(MARK)]
    for p in stale:
        p.unlink()
    print(f"wrote {len(written)} wiki pages; sidebar and Home tutorial blocks updated; "
          f"{len(POINTERS)} reference pages point to their lessons; {len(stale)} stale generated pages deleted")
    for p in stale:
        print(f"  deleted wiki/{p.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
