#!/usr/bin/env python3
"""Write the tutorial into the wiki: one page per lesson, one per track, a Start Here page, and the
tutorial blocks at the top of the sidebar and Home.

    python3 site/learn_export.py          # then: python3 wiki/check.py --strict && bash wiki/sync.sh

The source is site/content/learn/. The site copy is canonical and indexed; this copy is the mirror
on GitHub, where the boards are screenshots (site/tools/shoot.mjs) inside a <picture> that follows
the reader's colour mode. Every generated page starts with a marker, and the exporter refuses to
overwrite any wiki page that does not carry it — so a lesson can never replace a hand-written page.
The sidebar and Home keep everything outside their marked tutorial block.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
sys.path.insert(0, str(SITE))
from pages import learn  # noqa: E402

WIKI = SITE.parent / "wiki"
MARK = "<!-- generated by site/learn_export.py from site/content/learn — edit the source, not this page -->"
BLOCK = re.compile(r"<!-- tutorial:start[^>]*-->[\s\S]*?<!-- tutorial:end -->\n?")


def picture(key: str, les_url: str, reg: dict) -> str:
    name = learn.shot_name(key)
    alt = reg[key]["alt"].replace('"', "&quot;")
    return (f'<p align="center"><a href="{les_url}"><picture>'
            f'<source media="(prefers-color-scheme: dark)" srcset="{learn.SHOTS}{name}.dark.webp">'
            f'<img alt="{alt}" src="{learn.SHOTS}{name}.light.webp" width="100%">'
            f"</picture></a></p>\n\n<sub>▸ <a href=\"{les_url}\">Open the live, interactive version</a></sub>")


def body_for_wiki(md: str, link, les_url: str, reg: dict) -> str:
    out = []
    for line in md.splitlines():
        d = learn.DIRECTIVE.match(line.strip())
        out.append(picture(f"{d.group(1)}:{d.group(2)}", les_url, reg) if d else line)
    text = "\n".join(out)
    # resolve the tutorial's link schemes; leave fenced blocks alone
    parts = re.split(r"(```[\s\S]*?```)", text)
    for i in range(0, len(parts), 2):
        parts[i] = re.sub(r"\]\(((?:lesson|track|wiki|site|repo|sim):[^)\s]*)\)",
                          lambda m: "](" + link(m.group(1)) + ")", parts[i])
    return "".join(parts)


def lesson_page(les, lessons, tracks, reg) -> str:
    link = learn.Links("wiki", lessons, tracks)
    t = les.track
    body = body_for_wiki(les.body, link, les.url, reg)
    if link.problems:
        sys.exit(f"{les.slug}: " + "; ".join(sorted(set(link.problems))))
    prev = f"[← {les.prev.short}]({les.prev.wiki})" if les.prev else "[← Start here](Start-Here)"
    nxt = f"[{les.next.short} →]({les.next.wiki})" if les.next else "[Back to Start here →](Start-Here)"
    return f"""{MARK}
# {les.title}

*{les.dek}*

**{learn.minutes(les.body)} min read** · {les.level} · Lesson {les.n} of {len(t.lessons)} in [{t.title}]({t.wiki}) · Updated {learn.fmt_date(les.updated)} · [Read it on the site, with live diagrams ↗]({les.url})

{body}

---

| | |
| :--- | ---: |
| {prev} | {nxt} |

**[All lessons](Start-Here)** · **[{t.title}]({t.wiki})** · [This lesson on the site]({les.url})
"""


def track_page(t, tracks) -> str:
    k = tracks.index(t)
    rows = "\n".join(f"| {l.n} | **[{l.title}]({l.wiki})** | {l.description} | {learn.minutes(l.body)} min |"
                     for l in t.lessons)
    total = sum(learn.minutes(l.body) for l in t.lessons)
    nxt = tracks[k + 1] if k + 1 < len(tracks) else None
    after = f"**Next track:** [{nxt.title}]({nxt.wiki}) · " if nxt else ""
    return f"""{MARK}
# {t.title}

{t.blurb}

**{len(t.lessons)} lessons · about {total} minutes** · {t.promise} · [This track on the site ↗]({t.url})

| # | Lesson | What it covers | Time |
| --- | --- | --- | --- |
{rows}

{after}**[All lessons](Start-Here)**
"""


def contents(tracks) -> str:
    """The whole curriculum as one table of contents, mysqltutorial-style."""
    blocks = []
    for k, t in enumerate(tracks, 1):
        total = sum(learn.minutes(l.body) for l in t.lessons)
        items = "\n".join(f"{l.n}. **[{l.title}]({l.wiki})** — {learn.minutes(l.body)} min" for l in t.lessons)
        blocks.append(f"### {k} · [{t.title}]({t.wiki})\n\n*{t.blurb}* — {len(t.lessons)} lessons, "
                      f"about {total} minutes.\n\n{items}")
    return "\n\n".join(blocks)


def start_page(lessons, tracks, reg) -> str:
    smeta, sbody = learn._front((learn.LEARN / "start-here.md").read_text(encoding="utf-8"), "start-here.md")
    link = learn.Links("wiki", lessons, tracks)
    start_url = f"{learn.BASE_URL}learn/"
    body = body_for_wiki(sbody, link, start_url, reg)
    n = sum(len(t.lessons) for t in tracks)
    return f"""{MARK}
# {smeta['title']}

*{smeta['dek']}*

**Free · {n} lessons · by {learn.AUTHOR}** · [Read it on the site, with live diagrams ↗]({start_url})

{body}

## Every lesson, in order

{contents(tracks)}

---

**Also here:** the playbook's full reference — [The Agentic PDLC](The-Agentic-PDLC), [the role pages](Role-Product-Manager),
[the journeys](Journey-Product-Manager), [the how-tos](How-to-Prove-the-Bar), [Formulas](Formulas-and-Calculators)
and [the Glossary](Playbook-Glossary). Every lesson links into them where you need the depth.
"""


def sidebar_block(tracks) -> str:
    groups = []
    for t in tracks:
        items = "\n".join(f"{l.n}. [{l.short}]({l.wiki})" for l in t.lessons)
        groups.append(f"<details open><summary><b>{t.title}</b></summary>\n\n{items}\n\n</details>")
    return ("<!-- tutorial:start · generated by site/learn_export.py -->\n"
            "### 📘 Learn the agentic PDLC\n\n"
            "**[▶ Start here](Start-Here)**\n\n"
            + "\n\n".join(groups) +
            f"\n\n[All lessons, on the site ↗]({learn.BASE_URL}learn/)\n\n---\n<!-- tutorial:end -->\n")


def home_block(tracks) -> str:
    n = sum(len(t.lessons) for t in tracks)
    rows = "\n".join(f"| **[{t.title}]({t.wiki})** | {t.blurb} | {len(t.lessons)} |" for t in tracks)
    first = tracks[0].lessons[0]
    return f"""<!-- tutorial:start · generated by site/learn_export.py -->
# Learn the agentic PDLC

A free tutorial in short lessons on running software projects where an AI model does part of the
work — the four phases, the one hard gate, the eight loops, and how AWS AI-DLC, AIDD, the BMAD
Method and spec-driven development fit onto them. Each lesson is five to ten minutes, opens with the
answer, carries a picture, and credits its sources.

**[▶ Start here](Start-Here)** · or go straight to **[{first.title}]({first.wiki})**

| Track | What it covers | Lessons |
| --- | --- | --- |
{rows}

*{n} lessons so far.* The same tutorial, with live diagrams, is at [akash-coded.github.io/…/learn]({learn.BASE_URL}learn/).

---

<!-- tutorial:end -->
"""


def put_block(path: Path, block: str, after: str | None = None) -> None:
    text = path.read_text(encoding="utf-8")
    if BLOCK.search(text):
        text = BLOCK.sub(block, text, count=1)
    elif after and after in text:
        i = text.index(after) + len(after)
        text = text[:i] + "\n\n" + block + text[i:].lstrip("\n")
    else:
        text = block + "\n" + text
    path.write_text(text, encoding="utf-8")


def write(path: Path, text: str) -> None:
    if path.exists() and not path.read_text(encoding="utf-8").startswith(MARK):
        sys.exit(f"refusing to overwrite hand-written wiki page {path.name}")
    path.write_text(text, encoding="utf-8")


def main() -> int:
    meta, tracks, lessons = learn.load()
    errors, _ = learn.validate(meta, tracks, lessons)
    if errors:
        sys.exit("fix the lessons first (python3 site/build.py shows why):\n  " + "\n  ".join(errors))
    reg = learn._visuals()
    missing = [k for k in learn.used_visuals()
               if not (SITE / "assets" / "learn" / f"{learn.shot_name(k)}.light.webp").exists()]
    if missing:
        sys.exit("screenshots missing for " + ", ".join(missing) + " — run site/tools/shoot.mjs")
    written = []
    for t in tracks:
        write(WIKI / f"{t.wiki}.md", track_page(t, tracks))
        written.append(t.wiki)
        for les in t.lessons:
            write(WIKI / f"{les.wiki}.md", lesson_page(les, lessons, tracks, reg))
            written.append(les.wiki)
    write(WIKI / "Start-Here.md", start_page(lessons, tracks, reg))
    written.append("Start-Here")
    put_block(WIKI / "_Sidebar.md", sidebar_block(tracks), after="**[🏠 Wiki Home](Home)**")
    put_block(WIKI / "Home.md", home_block(tracks))
    # a generated page whose lesson was removed or renamed would linger; name it so it can be deleted
    stale = [p.name for p in WIKI.glob("*.md") if p.stem not in written
             and p.read_text(encoding="utf-8").startswith(MARK)]
    print(f"wrote {len(written)} wiki pages; sidebar and Home tutorial blocks updated")
    for s in stale:
        print(f"  stale generated page, delete it: wiki/{s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
