#!/usr/bin/env python3
"""Put the site's pictures on the hand-written wiki pages, in place of their mermaid fences.

    python3 site/wiki_pictures.py        # after `python3 site/build.py --shots` and tools/shoot.mjs

Each page lists, in order, the picture that replaces each of its mermaid fences. The first run
swaps a fence for a marker-owned block:

    <!-- picture:wikimap:anti-patterns -->
    <p align="center">…<picture>…</picture>…</p>
    <!-- /picture -->

Later runs regenerate the block between the markers, so the page stays hand-written everywhere
else. A key that names a lesson map, board or figure links to its live page; a wiki-only picture
links to its own full-size image.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
sys.path.insert(0, str(SITE))
sys.path.insert(0, str(SITE / "pages"))

from pages import learn  # noqa: E402

WIKI = SITE.parent / "wiki"

# page -> the picture for each mermaid fence, in the order the fences appear
PAGES: dict[str, list[str]] = {
    "Anti-Patterns": ["wikimap:anti-patterns"],
    "Decision-Trees": ["map:p0-frame", "wikimap:dt-exact", "wikimap:dt-autonomy", "map:the-hard-gate", "wikimap:dt-agents",
                       "wikimap:dt-prompt-or-signature", "wikimap:dt-review-band", "wikimap:dt-cache", "wikimap:dt-tier",
                       "wikimap:depth-of-change", "wikimap:dt-ship"],
    "Error-Index": ["wikimap:error-index"],
    "Formulas-and-Calculators": ["wikimap:formulas"],
    "Gates-and-Governance": ["map:ai-governance-gates", "map:the-hard-gate"],
    "How-to-Choose-Build-Buy-or-Borrow": ["wikimap:choose"],
    "How-to-Control-the-Token-Bill": ["wikimap:control-bill"],
    "How-to-Cut-Sprints-into-Bolts": ["wikimap:cut-sprints", "figure:bolt_days"],
    "How-to-Design-an-Agent-on-Paper": ["wikimap:design-agent", "map:p0-frame", "wikimap:agent-topology"],
    "How-to-Hold-the-Security-Boundary": ["wikimap:hold-boundary"],
    "How-to-Prove-the-Bar": ["wikimap:prove-bar"],
    "How-to-Review-by-Risk-Band": ["wikimap:review-band"],
    "How-to-Run-a-Missing-Control-Postmortem": ["wikimap:postmortem"],
    "How-to-Run-an-NFR-Workshop": ["wikimap:nfr-workshop"],
    "Mental-Models": ["wikimap:mental-models"],
    "Role-DevOps": ["wikimap:role-devops"],
    "Role-Engineering-Lead": ["wikimap:role-engineering-lead"],
    "Role-Product-Manager": ["wikimap:role-product-manager"],
    "Role-QA-Lead": ["wikimap:role-qa-lead"],
    "Role-Solution-Architect": ["wikimap:role-solution-architect"],
    "Role-Sponsor": ["wikimap:role-sponsor"],
    "Scenario-Library": ["wikimap:scenario-library"],
    "Sources-and-Confidence": ["wikimap:sources"],
    "Study-Plans": ["wikimap:study-plans"],
    "The-Agentic-PDLC": ["frameworks:spine", "board:loops", "wikimap:depth-of-change"],
    "The-Eight-Loops": ["wikimap:eight-loops-workshop", "wikimap:eight-loops-proof"],
    "The-Evidence-Pack": ["map:the-evidence-pack"],
    "Where-do-I-find-it": ["wikimap:where-do-i-find-it"],
}
# the journey pages are generated by wiki_export.py, which asks for these
JOURNEYS = {rid: f"wikimap:journey-{rid}" for rid in ("product-manager", "solution-architect", "engineering", "qa", "devops")}

FENCE = re.compile(r"```mermaid\n[\s\S]*?\n```\n?")
BLOCK = re.compile(r"<!-- picture:([a-z_:-]+) -->[\s\S]*?<!-- /picture -->\n?")


def keys() -> list[str]:
    """Every picture the wiki asks for, so the shots page can carry them all."""
    seen: list[str] = []
    for ks in list(PAGES.values()) + [list(JOURNEYS.values())]:
        for k in ks:
            if k not in seen:
                seen.append(k)
    return seen


def picture(key: str, reg: dict | None = None) -> str:
    """The marker-owned block for one picture."""
    reg = reg or learn._visuals()
    v = reg[key]
    name = learn.shot_name(key)
    light, dark = f"{learn.SHOTS}{name}.light.webp", f"{learn.SHOTS}{name}.dark.webp"
    alt = v["alt"].replace('"', "&quot;")
    live = v.get("live") or ""
    href = f"{learn.BASE_URL}{live}" if live and not key.startswith("wikimap:") else light
    foot = (f'<sub>▸ <a href="{href}">Open the live, interactive version</a></sub>'
            if href != light else f'<sub>▸ <a href="{light}">Open the picture full size</a></sub>')
    return (f"<!-- picture:{key} -->\n"
            f'<p align="center"><a href="{href}"><picture>'
            f'<source media="(prefers-color-scheme: dark)" srcset="{dark}">'
            f'<img alt="{alt}" src="{light}" width="100%"></picture></a></p>\n\n'
            f"{foot}\n<!-- /picture -->\n")


def apply(page: str, wanted: list[str], reg: dict) -> tuple[int, int]:
    path = WIKI / f"{page}.md"
    text = path.read_text(encoding="utf-8")
    have = [m.group(1) for m in BLOCK.finditer(text)]
    swapped = regenerated = 0
    # regenerate the blocks already there
    def regen(m: re.Match) -> str:
        nonlocal regenerated
        regenerated += 1
        return picture(m.group(1), reg)
    text = BLOCK.sub(regen, text)
    # then swap the remaining fences, in order, for the keys not yet placed
    for key in wanted:
        if key in have:
            continue
        if not FENCE.search(text):
            sys.exit(f"{page}.md: no mermaid fence left for {key}")
        text = FENCE.sub(picture(key, reg), text, count=1)
        swapped += 1
    path.write_text(text, encoding="utf-8")
    return swapped, regenerated


def main() -> int:
    reg = learn._visuals()
    missing = [k for k in keys() if k not in reg]
    if missing:
        sys.exit("unknown pictures: " + ", ".join(missing))
    from pathlib import Path as _P
    assets = SITE / "assets" / "learn"
    for k in keys():
        for mode in ("light", "dark"):
            if not (assets / f"{learn.shot_name(k)}.{mode}.webp").exists():
                sys.exit(f"no screenshot for {k} ({mode}); run build.py --shots and tools/shoot.mjs first")
    s = r = 0
    for page, wanted in PAGES.items():
        a, b = apply(page, wanted, reg)
        s += a
        r += b
    left = sum(len(FENCE.findall((WIKI / f"{p}.md").read_text(encoding="utf-8"))) for p in PAGES)
    print(f"{len(PAGES)} pages: {s} fences swapped, {r} blocks regenerated, {left} mermaid fences left")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
