#!/usr/bin/env python3
"""Check the wiki before it is pushed. Run from anywhere:

    python3 wiki/check.py            # report
    python3 wiki/check.py --strict   # non-zero exit on any problem

The wiki has no CI of its own — it is a separate git repository with no review — so this is the
only gate it gets. It checks the things that actually break on GitHub's renderer:

* internal links point at a page that exists (bare page names, no extension)
* in-page anchors match a heading on that page, using GitHub's slug rules
* ``<details>`` blocks and code fences are balanced
* mermaid blocks are fenced as ``mermaid`` and declare a diagram type
* tables have a separator row, which is what silently turns a table into a paragraph
* code inside a ``python`` / ``json`` fence parses, with ``<placeholders>`` substituted

It deliberately ignores links inside fenced blocks: those are template placeholders, not links.
"""
from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path

WIKI = Path(__file__).resolve().parent
FENCE = re.compile(r"(?P<f>```+|~~~+)[^\n]*\n[\s\S]*?(?P=f)")
# Scoreboard is generated by the Pulse workflow and is not in the seed.
EXTRA_PAGES = {"Scoreboard"}


def slug(heading: str) -> str:
    """GitHub's anchor rule: lowercase, drop non-alphanumerics except spaces and hyphens."""
    s = re.sub(r"<[^>]+>", "", heading)
    s = re.sub(r"[^a-z0-9 -]", "", s.lower()).strip()
    return s.replace(" ", "-")


def strip_fences(text: str) -> str:
    return FENCE.sub(lambda m: "\n" * m.group(0).count("\n"), text)


def check_code(text: str, name: str) -> list[str]:
    out = []
    for m in re.finditer(r"```(python|json)\n([\s\S]*?)```", text):
        lang, body = m.group(1), m.group(2)
        probe = re.sub(r"<[^>\n]{1,60}>", "PLACEHOLDER", body)
        try:
            ast.parse(probe) if lang == "python" else json.loads(probe)
        except Exception as exc:  # noqa: BLE001 - any parse failure is the finding
            line = text[: m.start()].count("\n") + 1
            out.append(f"{name}:{line}: {lang} block does not parse: {str(exc).splitlines()[0][:90]}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--strict", action="store_true", help="exit non-zero when anything is wrong")
    args = ap.parse_args()

    files = sorted(p for p in WIKI.glob("*.md") if p.name != "README.md")
    pages = {p.stem for p in WIKI.glob("*.md")} | EXTRA_PAGES
    problems: list[str] = []
    stats = []

    for f in files:
        text = f.read_text(encoding="utf-8")
        prose = strip_fences(text)
        name = f.name
        # headings inside a fenced block are template content, not anchors on this page
        heads = {slug(h) for h in re.findall(r"^#{1,6}\s+(.+)$", prose, re.M)}

        for m in re.finditer(r"\[[^\]]*\]\(([^)\s]+)\)", prose):
            link = m.group(1)
            if link.startswith(("http://", "https://", "mailto:")):
                continue
            target, _, anchor = link.partition("#")
            if target and target not in pages:
                problems.append(f"{name}: link to missing page '{target}'")
            if anchor and not target and anchor not in heads:
                problems.append(f"{name}: anchor '#{anchor}' matches no heading here")

        opened = len(re.findall(r"<details(?:\s[^>]*)?>", text))   # <details open> counts too
        if opened != text.count("</details>"):
            problems.append(f"{name}: unbalanced <details> "
                            f"({opened} open, {text.count('</details>')} close)")
        if text.count("```") % 2:
            problems.append(f"{name}: odd number of ``` fences")
        for m in re.finditer(r"```mermaid\n([\s\S]*?)```", text):
            if not re.match(r"\s*(flowchart|graph|sequenceDiagram|stateDiagram|classDiagram|erDiagram|gantt|pie|journey|mindmap|timeline)",
                            m.group(1)):
                problems.append(f"{name}: mermaid block does not start with a diagram type")
        # a table row followed by a non-separator is the classic silent break
        lines = prose.splitlines()
        for i, line in enumerate(lines[:-1]):
            if line.strip().startswith("|") and line.count("|") >= 3:
                nxt = lines[i + 1].strip()
                prev = lines[i - 1].strip() if i else ""
                if not prev.startswith("|") and not re.match(r"^\|[\s:|-]+\|$", nxt):
                    problems.append(f"{name}:{i+1}: table header has no separator row")
        problems += check_code(text, name)

        stats.append((name, len(text.splitlines()),
                      text.count("<summary><b>Template"), text.count("<summary><b>Prompt"),
                      text.count("```mermaid")))

    width = max(len(s[0]) for s in stats)
    print(f"{'page':{width}}  lines  tmpl  prmt  mmd")
    for name, n, tpl, pr, mmd in stats:
        print(f"{name:{width}}  {n:5}  {tpl:4}  {pr:4}  {mmd:3}")
    total = sum(s[1] for s in stats)
    print(f"\n{len(stats)} pages · {total:,} lines · {sum(s[2] for s in stats)} templates · "
          f"{sum(s[3] for s in stats)} prompts · {sum(s[4] for s in stats)} diagrams")

    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print("  " + p)
        return 1 if args.strict else 0
    print("\nno problems")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
