#!/usr/bin/env bash
# Seed or restore the GitHub wiki from wiki/*.md
#
# The wiki's git repo does not exist until the first page is created in the web
# UI. If this fails with "Repository not found", that is what has happened —
# create any page at the /wiki URL first, then re-run.
#
# This OVERWRITES the wiki. It is a seed/restore, not a sync — so it first refuses to run over any page
# someone edited in the browser since the last seed, unless the repository already has that edit.
# FORCE=1 bash wiki/sync.sh overwrites them anyway.
set -euo pipefail

REPO="akash-coded/aws-bedrock-agentcore-strands"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if ! command -v gh >/dev/null; then echo "needs the gh CLI"; exit 1; fi
TOKEN="$(gh auth token)"
URL="https://x-access-token:${TOKEN}@github.com/${REPO}.wiki.git"

echo "Cloning the wiki…"
if ! git clone --quiet "$URL" "$TMP/wiki" 2>/dev/null; then
  cat <<'MSG'

The wiki repository does not exist yet.

GitHub creates it only when the first page is saved in the web UI — there is no
API for this, and pushing to an unseeded wiki fails.

  1. Open  https://github.com/akash-coded/aws-bedrock-agentcore-strands/wiki
  2. Click "Create the first page", save anything at all
  3. Re-run this script

MSG
  exit 1
fi

# Edits made on the live wiki since the last seed: each page changed since that commit must already be
# in wiki/ byte for byte, or this would silently undo someone's work. Scoreboard.md is the Pulse
# workflow's, and is never seeded.
LAST="$(git -C "$TMP/wiki" log --format=%H --grep='^Seed wiki from repository' -n 1 || true)"
if [ -n "$LAST" ]; then
  UNSAVED=()
  while IFS= read -r f; do
    [ -z "$f" ] || [ "$f" = "Scoreboard.md" ] && continue
    if [ ! -f "$TMP/wiki/$f" ] || [ ! -f "$HERE/$f" ] || ! cmp -s "$TMP/wiki/$f" "$HERE/$f"; then
      UNSAVED+=("$f")
    fi
  done < <(git -C "$TMP/wiki" diff --name-only "$LAST" HEAD -- '*.md')
  if [ "${#UNSAVED[@]}" -gt 0 ] && [ "${FORCE:-0}" != "1" ]; then
    echo
    echo "The live wiki has edits that wiki/ does not. Syncing now would erase them:"
    for f in "${UNSAVED[@]}"; do
      echo "  $f — $(git -C "$TMP/wiki" log -1 --format='%an, %ad' --date=short "$LAST"..HEAD -- "$f")"
    done
    echo
    echo "Bring each one home first: a hand-written page into wiki/, a generated one (it starts with"
    echo "'generated by site/learn_export.py') into its lesson under site/content/learn/. The Wiki edits"
    echo "workflow opens an issue for each such edit. To overwrite them anyway: FORCE=1 bash wiki/sync.sh"
    exit 1
  fi
fi

# Scoreboard.md is owned by the Pulse workflow, not this seed — leave it alone
find "$TMP/wiki" -maxdepth 1 -name '*.md' ! -name 'Scoreboard.md' -delete
cp "$HERE"/*.md "$TMP/wiki/"
rm -f "$TMP/wiki/README.md"          # the seed README stays in the repo only

cd "$TMP/wiki"
if git diff --quiet && git diff --cached --quiet && [ -z "$(git status --porcelain)" ]; then
  echo "Wiki already matches the seed. Nothing to do."; exit 0
fi
git add -A
git commit --quiet -m "Seed wiki from repository wiki/ directory" \
  -m "Repository commit $(git -C "$HERE" rev-parse --short HEAD)"
git push --quiet origin HEAD
echo "Pushed $(ls "$HERE"/*.md | grep -v README | wc -l | tr -d ' ') pages."
echo "https://github.com/${REPO}/wiki"
